### ISSUE TITLE
Would you like to add meta info in the header which can use melpa recipe to install your package?

### ISSUE THREAD

**Issue by enzochiau** [caiorss/org-wiki#3]
I am using Spacemacs and try to install your package through melpa recipe. But it failed because of lacking of header info in your package. 

Do you have plan to add the meta info later which can make the install process work?

**Comment by caiorss** [comment]
> But it failed because of lacking of header info in your package. 

Well, it is my first package. I don't know how to create a melpa recipe yet. Could you provide some link about *melpa info header* or some template or example ? 

While it is not ready you can just download the *.el file and put in any directory listed in the load-path variable and add (require 'org-wiki).

> Do you have plan to add the meta info later which can make the install process work?

Yes. But this package is still experimental and plan to add new features like a command to download files to attachment/assets directory of a page and a command to paste pictures.

**Comment by caiorss** [comment]
Ok. I added the header.

**Comment by enzochiau** [comment]
Tested. It works now.
