### ISSUE TITLE
Option to create new folder for every wiki page creation?

### ISSUE THREAD

**Issue by Cumol** [caiorss/org-wiki#7]
Great package! I am using it to write a labbook (will write a blogpost about my setup eventually).

Do you think that there is a way to create a folder containing the .org file for every new wiki page? If I was to do this, where do I start to modify the code to do so?

Thanks in advance!

**Comment by caiorss** [comment]
Do you mean create the attachment/asset directory fo the wiki page. For instance for the file 
 - ~/wiki-location/Linux.org create the directory ~/wiki-location/Linux ? 

Did this commit address your issue - https://github.com/caiorss/org-wiki/commit/9a719263275d29c68e41945802b3e339016fc5ff ?

>  If I was to do this, where do I start to modify the code to do so?

It is possible by modifying the function org-wiki/open-page that is invoked when you open a wiki:pagename hyperlink.
