### ISSUE TITLE
Issue with org-wiki-paste-image

### ISSUE THREAD

**Issue by schuach** [caiorss/org-wiki#8]
First I have to say that I like your package very much! I hope to see it on MELPA soon.

I've been experiencing issues with org-wiki-paste-image . I always have to enter the whole path to the file, because in helm not the org-wiki-location but the location of my emacs-binaries is prepended to dir. For example when I try to paste an image to index.org, the helm-promt for the filename looks like this:
![wrong_path](https://cloud.githubusercontent.com/assets/6453037/21235500/51175e28-c2f7-11e6-8202-6442ef6a7ade.png)

I do think I have a fix though. It works for me, but I am not a programmer, so I can't tell if it's a very good one: The docstring of read-file-name says, that one should provide an absolute directory name for DIR. In line 793 of org-wiki.el, dir is only passed the name of the directory, not the whole path. I have modified the line to:
      
       `(file (read-file-name "Image: " (concat org-wiki-location "/" dir))))`

Now read-file-name sees the full directory name and it works for me.

Would it make sense for you to make that change to org-wiki.el?

Thanks and best regards,
Stefan

**Comment by caiorss** [comment]
Ok. I've fixed it. Check out this new release. Thanks for the bug report.

**Comment by schuach** [comment]
Work fine now, thank you!
